// This file is needed for Firebase initialization
// In a real project, it would be generated by the Firebase CLI

import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Default options for development
    return const FirebaseOptions(
      apiKey: 'AIzaSyDMi4LFPStM2KHEJVOGTlb_zJ-l7piLENw',
      appId: '1:507921827121:ios:3687f57fc2fda956a2dc10',
      messagingSenderId: '507921827121',
      projectId: 'sugram-ios',
      storageBucket: 'sugram-ios.firebasestorage.app',
      authDomain: 'sugram-ios.firebasestorage.app',
    );
  }
}